### ISSUE TITLE
sending data to neo4j

### ISSUE THREAD

**Issue by garanews** [yampelo/beagle#25]
Following the guide in order to use Neo4J I eported these variables (passing through -e in docker run...) :
BEAGLE__GENERAL__LOG_LEVEL=DEBUG
BEAGLE__NEO4J__HOST=bolt://my_neo4j_ip:7687
BEAGLE__NEO4J__USERNAME=myuser
BEAGLE__NEO4J__PASSWORD=mypwd

I am able to see the debug messages, but there is no communication with Neo4j.
I see 
INFO | Initialized NetworkX Backend
Am I missing something?
I tried also to use docker-compose with same variables under "environment" but result is the same.
Thanks

**Comment by garanews** [comment]
I dont find in the code a place to change the backend...

**Comment by yampelo** [comment]
You need to use the python bindings to send to neo4j:

```python
from beagle.backends import Neo4J
from beagle.datasources import HXTriage

HXTriage(...).to_graph(backend=Neo4J)

```

https://github.com/yampelo/beagle#python-library

Fair warning, my cypher is awful and there may be a way way way better to set it up to send to neo4j, if you guys have more experience you should totally contribute a better way to transform the node classes to batch cypher upload queries 😄

**Comment by garanews** [comment]
I installed (not so easy) beagle  outside docker with pipenv in order to modify code faster.
I'm looking the base_transformer.py should I set there Neo4j instead networkx?

**Comment by yampelo** [comment]
Are you trying to use the web interface to upload to Neo4J? That won't work, you need to use the bindings like above. The web interface is meant to be a self-contained thing, where you upload a triage, it transforms it to a NetworkX object, saves it in the database, then redirects you to the web interface for it.

Try calling the python library directly like in my example above.

**Comment by garanews** [comment]
>>> from beagle.backends import Neo4J
>>> from beagle.datasources import HXTriage
>>> backend = HXTriage('EA9OgF2nOpkgoI4Em15jMy.mans').to_graph(backend=NEO4J)
2019-04-19T14:10:56 | beagle.datasources.hx_triage.__init__:53 | INFO | Setting up HXTriage for EA9OgF2nOpkgoI4Em15jMy.mans
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'NEO4J' is not defined
>>>

**Comment by garanews** [comment]
having some issue passing db parameters:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/beagle-ZloiBEyB/lib/python3.6/site-packages/beagle/datasources/base_datasource.py", line 111, in to_graph
    return self.to_transformer(self.transformers[0]).to_graph(*args, **kwargs)  # type: ignore
  File "/root/.local/share/virtualenvs/beagle-ZloiBEyB/lib/python3.6/site-packages/beagle/transformers/base_transformer.py", line 60, in to_graph
    backend = backend(nodes=nodes, metadata=self.datasource.metadata(), *args, **kwargs)
  File "/root/.local/share/virtualenvs/beagle-ZloiBEyB/lib/python3.6/site-packages/beagle/backends/neo4j.py", line 38, in __init__
    self.neo4j = GraphDatabase(uri, auth=(username, password))
TypeError: object() takes no parameters
>>>


passing manually someghing changes:
backend = HXTriage('/home/users/analyst/dsadadm15jMy.mans').to_graph(backend=Neo4J, uri="bolt://12.3.4:7687", auth=("neo4j","password"))

2019-04-19T15:00:42 | beagle.transformers.base_transformer.run:111 | INFO | Finished processing of events, created 8838 nodes.
2019-04-19T15:00:42 | beagle.backends.neo4j.__init__:36 | INFO | Connecting to neo4j server at bolt://1.2.3.4:7687
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/beagle-ZloiBEyB/lib/python3.6/site-packages/beagle/datasources/base_datasource.py", line 111, in to_graph
    return self.to_transformer(self.transformers[0]).to_graph(*args, **kwargs)  # type: ignore
  File "/root/.local/share/virtualenvs/beagle-ZloiBEyB/lib/python3.6/site-packages/beagle/transformers/base_transformer.py", line 60, in to_graph
    backend = backend(nodes=nodes, metadata=self.datasource.metadata(), *args, **kwargs)
  File "/root/.local/share/virtualenvs/beagle-ZloiBEyB/lib/python3.6/site-packages/beagle/backends/neo4j.py", line 38, in __init__
    self.neo4j = GraphDatabase(uri, auth=(username, password))
TypeError: object() takes no parameters
>>>

**Comment by yampelo** [comment]
Seems like the Neo4J has a couple of bugs with it since I had to move over from `py2neo` to the official neo4j driver. I might not be able to debug until this weekend due to travel, do you wanna chat about it on slack? : https://join.slack.com/t/beaglegraph/shared_invite/enQtNjE1MzQyNTE3NTI3LTUzMGNhMzcwN2M5ODg3NGRmNzVmM2ZjMmU0NDk3ODEwMmRkZjEyZWIxYzU5NmM3MWMxOWU4MjVhNWEyNWVkNTI

**Comment by garanews** [comment]
Sure, I joined in slack (I'm also on gitter, same user)
on other projects I am running py2neo (4.x).
Take your time, now Easter times :)
Thanks

**Comment by yampelo** [comment]
Hey @garanews , i finally finished my finals week and had time to check this out. I got it working!

![image](https://user-images.githubusercontent.com/6065272/58518336-ce627e80-817c-11e9-9fdb-3b3d6aa9e30e.png)

**Comment by yampelo** [comment]
The version on pypi (`pip install pybeagle --upgrade`) will allow it to work

**Comment by garanews** [comment]
Hello, 
thanks, going to try it immediately!
Now it would be useful sending data from ui directly to neo4j :)

**Comment by yampelo** [comment]
Opened #41 to track it, it should be pretty straight forward to do.
