### ISSUE TITLE
PCAP Display Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by jdubp** [yampelo/beagle#66]
I supplied Beagle a pcap from Malware-Traffic-Analysis and received the below error. Anyone else experiencing issues with importing PCAPs? 

2019-10-30T15:13:34 | beagle.web.api.views.new:357 | INFO | Finished generating graph
[2019-10-30 15:13:34,373] ERROR in app: Exception on /api/new [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/beagle/beagle/web/api/views.py", line 370, in new
    json.dumps(graph.to_json(), sort_keys=True).encode("utf-8")
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

**Comment by yampelo** [comment]
Can you share the pcap?

**Comment by jdubp** [comment]
Sure, this is the one used
http://malware-traffic-analysis.net/2019/09/06/2019-09-06-Qakbot-infection-traffic.pcap.zip

**Comment by yampelo** [comment]
Fixed via #63, pull down the newest image in about 30 minutes
